on:
  pull_request:
    branches:
      - main
    types: ["closed"]
jobs:
  qa-pipeline-job:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: checkout
        uses: actions/checkout@v3
      - name: qa-words action step
        uses: ./action-qa-words # Uses an action in the root directory
        id: qa-words
      # Use the output from the `qa-words action step` step
      - name: move issues to the QA pipeline
        uses: ./action-qa-pipeline # Uses an action in the root directory
        id: qa-pipeline
        with:
          issueIds: ${{steps.qa-words.outputs.*}}
